name: Test Enterprise Developer Setup  

on:  
  workflow_dispatch:  # This allows manual triggering  

jobs:  
  test-setup:  
    runs-on: self-hosted  
    steps:  
      - name: Check out repository  
        uses: actions/checkout@v3  
        
      - name: Test SetupEnv through wrapper script  
        shell: cmd  
        run: |  
          echo ======= TESTING ENTERPRISE DEVELOPER SETUP =======  
          echo Current Directory: %CD%  
          
          IF EXIST "Scripts\ed.bat" (  
            echo Found wrapper script: Scripts\ed.bat  
          ) ELSE (  
            echo ERROR: Wrapper script missing  
            exit 1  
          )  
          
          echo ======= CALLING WRAPPER SCRIPT =======  
          call Scripts\ed.bat
          
          echo ======= ENVIRONMENT CHECK =======  
          if defined COBDIR (  
            echo COBDIR=%COBDIR%  
            echo Setup successful  
          ) else (  
            echo Setup failed  
            exit 1  
          )
