name: Test Enterprise Developer Setup  

on:  
  workflow_dispatch:  # This allows manual triggering  

jobs:
  test-setup:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Test SetupEnv through wrapper script
        shell: cmd
        run: |
          echo ======= TESTING ENTERPRISE DEVELOPER SETUP =======
          echo Current Directory: %CD%

          IF EXIST "Scripts\ed.bat" (
            echo Found wrapper script: Scripts\ed.bat
          ) ELSE (
            echo ERROR: Wrapper script missing at Scripts\ed.bat
            exit /b 1
          )

          rem --- Optional: Check if the target SetupEnv.bat exists ---
          echo ======= PRE-CHECKING SetupEnv.bat LOCATION =======
          dir "%ProgramFiles(x86)%\Micro Focus\Enterprise Developer\SetupEnv.bat"

          echo ======= CALLING WRAPPER SCRIPT =======
          call Scripts\ed.bat
          set SCRIPT_EXIT_CODE=%ERRORLEVEL%
          echo ======= WRAPPER SCRIPT FINISHED (Exit Code: %SCRIPT_EXIT_CODE%) =======

          if %SCRIPT_EXIT_CODE% NEQ 0 (
            echo ERROR: Wrapper script Scripts\ed.bat failed with exit code %SCRIPT_EXIT_CODE%.
            exit /b %SCRIPT_EXIT_CODE%
          )

          rem --- If we get here, ed.bat exited with 0 (success) and should have set COBDIR via GITHUB_ENV ---
          echo ======= FINAL WORKFLOW ENVIRONMENT CHECK =======
          rem Check COBDIR - it should have been set via GITHUB_ENV by the script
          if defined COBDIR (
            echo COBDIR is defined: %COBDIR%
            echo Workflow step confirms setup successful.
          ) else (
            echo ERROR: COBDIR is NOT defined after script execution using GITHUB_ENV! Check script/runner logs.
            exit /b 1
          )
